### ISSUE TITLE
Message deletion issue

### ISSUE THREAD

**Issue by AceLikesGhosts** [iSlammedMyKindle/twitchToDiscordBot#20]
Reproduce:
1. Post 2 long messages past Twitch limit from Discord
2. Delete both

Doing so will cause the very first initial message to not delete.

**Comment by AceLikesGhosts** [comment]
Did this ever get fixed?

**Comment by iSlammedMyKindle** [comment]
I need to check; I'm going to be working on one last major project; so far no one has really tried to do this, so the usecase doesn't need priority yet
