### ISSUE TITLE
fix `config.json` being in the actual repo

### ISSUE THREAD

**Issue by AceLikesGhosts** [iSlammedMyKindle/twitchToDiscordBot#24]
leaking tokens and having to reset them arent fun, why was this never fixed 😭

**Comment by iSlammedMyKindle** [comment]
I have no idea what the solution to this problem would be - it's a small thing, but it does get annoying when the token is leaked.

It's probably something basic, might be worth looking into when the next major feature is put together.

**Comment by AceLikesGhosts** [comment]
it's already inside of the `.gitignore`, pretty sure all that would be needed is a simple `git rm config.json`

**Comment by AceLikesGhosts** [comment]
https://github.com/iSlammedMyKindle/twitchToDiscordBot/blob/master/.gitignore#L2
